packages:
  - "packages/*"

overrides:
  effect: 4.0.0
  "@effect/vitest": 4.0.0
  "@effect/atom-react": 4.0.0
  "@effect/platform-browser": 4.0.0
  "@effect/platform-node": 4.0.0
  "@effect/platform-node-shared": 4.0.0

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - effect
  - "@effect/vitest"
  - "@effect/atom-react"
  - "@effect/platform-browser"
  - "@effect/platform-node"
  - "@effect/platform-node-shared"
  - xstate-v6
