packages:
  - "."

overrides:
  effect: 4.0.0-rc.109
  "@effect/atom-react": 4.0.0-rc.109
  "@effect/vitest": 4.0.0-rc.109

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - effect
  - "@effect/atom-react"
  - "@effect/vitest"
