packages:
  - "."

overrides:
  effect: 4.0.0-beta.105
  "@effect/atom-react": 4.0.0-beta.105
  "@effect/vitest": 4.0.0-beta.105

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - effect@4.0.0-beta.105
  - "@effect/atom-react@4.0.0-beta.105"
  - "@effect/vitest@4.0.0-beta.105"
