import { Schema } from "effect"
import { describe, expect, test } from "tstyche"
import { Machine } from "../../src/index.js"

const root = Machine.state({
  fields: { count: Schema.Number },
  initial: "Editing",
  states: {
    Editing: { fields: { draft: Schema.String } },
    Saving: {}
  }
})
const events = Machine.events({ Increment: { by: Schema.Number }, Save: {} })

describe("root contracts", () => {
  test("preserves fields and child paths", () => {
    expect(root.path("")).type.toBe<"">()
    expect(root.path("Editing")).type.toBe<"Editing">()
    expect<Machine.Value<typeof root, "">>().type.toBe<{ readonly _tag: ""; readonly count: number }>()
    expect<Machine.Value<typeof root, "Editing">>().type.toBe<{ readonly _tag: "Editing"; readonly draft: string }>()
    expect(root.path).type.not.toBeCallableWith("Missing")
  })

  test("requires root values and default child values before execution", () => {
    // A valued root needs an initializer.
    // @ts-expect-error not assignable
    Machine.make({ root, events })
    const definition = Machine.make({ root, events, initial: (root) => root.from(() => ({ count: 0 })) })
    const incomplete = definition.handle({})
    // The default Editing state has no draft value yet.
    // @ts-expect-error MissingInitialImplementation
    Machine.start(incomplete)
    const complete = definition.handle({ initialize: ({ builder }) => builder.from({ draft: "" }) })
    expect(Machine.start).type.toBeCallableWith(complete)
  })

  test("reusing a root restores default initialization requirements", () => {
    const explicit = Machine.make({
      root,
      events,
      initialConfiguration: (root) => root.resolve(({ target }) => target.from({ count: 0 }, (to) => to.Saving.from()))
    }).handle({})
    expect(Machine.start).type.toBeCallableWith(explicit)
    const reused = Machine.make({ root: explicit.root, events, initial: (root) => root.from(() => ({ count: 0 })) })
      .handle({})
    // An override belongs to a machine, not its reusable root descriptor.
    // @ts-expect-error MissingInitialImplementation
    Machine.start(reused)
  })

  test("does not accept raw constructor shorthand or incompatible fields", () => {
    // fields and schema express different construction contracts.
    // @ts-expect-error not assignable
    Machine.state({ fields: { count: Schema.Number }, schema: Schema.TaggedStruct("Count", { count: Schema.Number }) })
    // Tags are generated by the event protocol.
    // @ts-expect-error EventProtocolError
    Machine.events({ Save: { _tag: Schema.String } })
    Machine.make({
      root,
      events,
      initial: (root) => {
        // Direct from takes a callback, not an object.
        // @ts-expect-error does not exist
        root.from({ count: 0 })
        // Root count is numeric.
        // @ts-expect-error not assignable
        root.from(() => ({ count: "zero" }))
        return root.from(() => ({ count: 0 }))
      }
    })
  })
})
