packages:
  - "."

overrides:
  effect: 4.0.0-rc.111
  "@effect/atom-react": 4.0.0-rc.111

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - effect
  - "@effect/atom-react"
  - vite@8.1.5
  - "@vitejs/plugin-react@6.0.4"
